var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                              $       xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                ",
   "                                                               xxxx!!!!!xxxxxxxx",
   "                                                                  xx v xx       ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",                                        
   "                                                                                ", 
   "                                           xxxxx            o           o       ",     
   "                                                     xxx   xxxxxx     xxxxxx    ",
   "           $xxx                o                                                ",
   "             xx           xxxxxxxxxxxx                                          ",
   "     @       xx           xx!!!!!!!!xx                                          ",
   "    xxx      xx           xxxxxxvxxxxx   xxx                                    ", 
   "    x x      xx                                  o                              ",
   "!!!!x x!!!!!!xx                                 xxx                             ",
   "!!!!x x!!!!!!xxxxx                                                              ",
   "!!!!x x!!!!!!xx                             $xxx                                ",
   "!!!!x x!!!!!!xx                                                                 ",
   "!!!!x x!!!!!!xx        o                                                        ",
   "!!!!x x!!!!!!xxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxx                                ",
   "!!!!x x!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],                                    												 
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                  xxxxxx    xxxxxx                                                                            ",
   "                  x!!=   o     !!x                                                                            ",
   "                  x!!    o    =!!x                                                                            ",
   "                  xxxxxx    xxxxxxxxxx         xxxxx                                    o                     ",
   "                                                                                                              ",
   "                                          xxx                                         xxxxxx                  ",
   "            xxxx                                                                                   o          ",
   "            xxxx                      xxxx               xxxx                    $xxxxxx         xxxxxx       ",
   "          xxx  x                                            x                 xxxxxx                          ",
   "            x  x                xxxxxx                      x$            xxxxx                               ",
   "  o      @  x  x           xxxxxx                           x    o   o    x                                   ", 
   "xxxx!!!!xxxxx  xxxxxxxxxxxxx                                xxxxxxxxxxxxxxx                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["                                                                                                           ",
   "                                      xxx															        ",
   "                                     x!!!x                                xxxx                              ",
   "                                     x!v!x                                x!!x                              ",
   "                                                                          xvvx                              ",
   "                                                                                                            ",
   "                                                       xxx                                                  ",
   "                                                       x x                                                  ",
   "                                                     xxx x                                                  ",
   "                                                      x  x$               x                                 ",
   "                                 o         o          x  x  o                                               ",
   "                                xxx       xxx      xxxx  xxxxxxxx                                           ",
   "                                                                                                            ",
   "                    x      xxx                                                                              ",
   "                    x                                                                                       ",
   "                    x o                                                xxx      xxx                         ",
   "                    xxxx                                                                     x              ",
   "                              xxx                                                          o x              ",
   "                                                                                         xxxxx              ",
   "                                     xxxxxx                                                                 ",
   "        xxxxx                                                                                               ",
   "                                                                                                            ",
   "  @               o           o                                                                             ",
   "xxxxx!!!!!!!!xxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                            "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
